name: Build luci-app-routewatch

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout luci-app-routewatch
        uses: actions/checkout@v3

      - name: Clone full OpenWrt source
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git --branch v24.10.0 --depth 1 buildroot

      - name: Set up feeds
        run: |
          cd buildroot
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy package into buildroot
        run: |
          mkdir -p buildroot/package/luci-app-routewatch
          rsync -av --exclude 'buildroot' --exclude '.github' ./ ./buildroot/package/luci-app-routewatch/

      - name: Cache build downloads and build_dir
        uses: actions/cache@v3
        with:
          path: |
            buildroot/dl
            buildroot/build_dir
          key: ${{ runner.os }}-openwrt-v24.10.0-${{ hashFiles('**/.config') }}

      - name: Configure OpenWrt build
        run: |
          cp .config buildroot/.config
          cd buildroot
          make defconfig

      - name: Build luci-app-routewatch
        run: |
          cd buildroot
          make package/luci-app-routewatch/compile -j$(nproc) V=s

      - name: Prepare IPK and generate index
        run: |
          mkdir -p publish
          cp buildroot/bin/packages/*/luci/luci-app-routewatch*.ipk publish/
          
          echo "=== IPK FILES ==="
          ls -l publish
          
          cd buildroot
          python3 ./scripts/gen_packages.py ../publish > ../publish/Packages
          gzip -k ../publish/Packages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./publish
