# .github/workflows/build.yml
name: Build luci-app-routewatch

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up OpenWRT SDK
        run: |
          mkdir buildroot
          cd buildroot
          wget https://downloads.openwrt.org/releases/24.10.0/targets/x86/64/openwrt-sdk-24.10.0-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar -xf openwrt-sdk-*.tar.zst
          mkdir sdk
          mv openwrt-sdk-24.10.0-x86-64_gcc-13.3.0_musl.Linux-x86_64/* sdk

      - name: Prepare SDK & Copy package
        run: |
          cd buildroot/sdk
          mkdir -p package/luci-app-routewatch
          rsync -av --exclude 'buildroot' --exclude '.github' $GITHUB_WORKSPACE/main package/luci-app-routewatch/

      - name: Debug package folder
        run: |
          ls -l $GITHUB_WORKSPACE/
          ls -l buildroot/sdk/
          ls -l buildroot/sdk/package/
          ls -l buildroot/sdk/package/luci-app-routewatch/

      - name: Build IPK
        run: |
          cp $GITHUB_WORKSPACE/.config buildroot/sdk/.config
          cd buildroot/sdk
          make defconfig
          make package/luci-app-routewatch/compile -j$(nproc) V=s

      - name: Prepare publish artifacts
        run: |
          mkdir -p publish
          find buildroot/sdk/bin/packages/ -name "luci-app-routewatch*.ipk" -exec cp {} publish/ \;
          cd publish
          apt-get update && apt-get install -y opkg-utils
          opkg-make-index . > Packages
          gzip -k Packages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./publish
